export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-8">
      <h1 className="text-4xl font-bold mb-4">Editorial E2E Test</h1>
      <p className="text-gray-600">Project generated by Specwright. Run the stories to build it out.</p>
    </main>
  );
}
