import { after } from "next/server";

import { Layout } from "../../components/Layout";
import { createRequestTimer, requestLogger } from "../../lib/logger";

export const dynamic = "force-dynamic";

export default function HomePage() {
  const requestTimer = createRequestTimer();

  try {
    after(() => {
      requestLogger.info("Request completed", {
        method: "GET",
        path: "/",
        responseTimeMs: requestTimer.durationMs(),
        routeType: "page",
        statusCode: 200,
        visibility: "public",
      });
    });
  } catch (error) {
    requestLogger.debug("Skipped request timing outside request scope", {
      error,
      path: "/",
      routeType: "page",
      visibility: "public",
    });
  }

  return (
    <Layout>
      <section className="max-w-3xl space-y-4">
        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-slate-500">
          Frontend Bootstrap
        </p>
        <h1 className="text-4xl font-semibold tracking-tight text-slate-950">
          Editorial Control Center
        </h1>
        <p className="text-lg leading-8 text-slate-600">
          Project generated by Specwright. This placeholder home page confirms the Next.js App
          Router shell is in place for the editorial control center.
        </p>
      </section>
    </Layout>
  );
}
