import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { beforeEach, describe, expect, it, vi } from "vitest";

import * as db from "../lib/db";
import {
  getDatabaseConnectionString,
  getDatabasePoolConfig,
  verifyDatabaseConnection,
} from "../lib/db";
import { GET } from "../app/api/health/route";
import Home from "../app/(app)/page";
import payloadConfig from "../payload.config";

describe("bootstrap smoke", () => {
  beforeEach(() => {
    vi.restoreAllMocks();
  });

  it("loads the payload config", async () => {
    const config = await payloadConfig;

    expect(config).toBeDefined();
    expect(config).toHaveProperty("db");
    expect(config).toHaveProperty("secret");
  });

  it("builds the shared database pool config from env", () => {
    expect(getDatabaseConnectionString()).toBe(process.env.DATABASE_URI);
    expect(getDatabasePoolConfig()).toMatchObject({
      connectionString: process.env.DATABASE_URI,
      connectionTimeoutMillis: 5_000,
      idleTimeoutMillis: 30_000,
      max: 10,
    });
    expect(typeof verifyDatabaseConnection).toBe("function");
  });

  it("returns a healthy response from the health route", async () => {
    vi.spyOn(db, "verifyDatabaseConnection").mockResolvedValue({
      currentDatabase: "editorial_control_center",
      ok: true,
    });

    const response = await GET();
    const body = await response.json();

    expect(response.status).toBe(200);
    expect(body).toMatchObject({
      database: {
        currentDatabase: "editorial_control_center",
        ok: true,
      },
      ok: true,
      service: "editorial-control-center",
      status: "ok",
    });
    expect(body.timestamp).toEqual(expect.any(String));
    expect(body.uptimeSeconds).toEqual(expect.any(Number));
  });

  it("home page smoke render includes the project title", () => {
    const html = renderToStaticMarkup(React.createElement(Home));

    expect(html).toContain("Editorial Control Center");
    expect(html).toContain("Project generated by Specwright");
    expect(html).toContain("Navigation placeholder");
  });

  it("home page module exports a renderable component", () => {
    expect(typeof Home).toBe("function");
  });
});
