"""Commands Engine.

Derives validation, setup, and development commands from
the project stack so that commands.json is pre-populated
and the ralph loop can validate from the first story.

This replaces the empty commands.json that was previously
generated by the openclaw bundle.
"""

from __future__ import annotations

from typing import Any


def generate_commands(spec: dict[str, Any]) -> dict[str, Any]:
    """Generate commands dict from the project spec.

    Returns a dict with:
    - commands: validation and dev commands the executor should use
    - setup: one-time setup commands to bootstrap the project
    - notes: guidance for the executor
    """
    stack = spec.get("stack", {})
    answers = spec.get("answers", {})
    capabilities = spec.get("capabilities", [])

    frontend = stack.get("frontend", "nextjs")
    backend = stack.get("backend", "node-api")
    database = stack.get("database", "postgres")
    deploy_target = answers.get("deploy_target", "docker")

    commands: dict[str, str] = {}
    setup: dict[str, str] = {}
    notes: list[str] = []

    # ---------------------------------------------------------------
    # Package manager — all current archetypes are Node.js-based
    # ---------------------------------------------------------------
    pkg_manager = "npm"

    # ---------------------------------------------------------------
    # Setup commands
    # ---------------------------------------------------------------
    setup["install"] = f"{pkg_manager} install"

    if database == "postgres":
        if deploy_target in ("docker", "docker_and_k8s_later"):
            setup["db_start"] = "docker compose up -d postgres"
        else:
            setup["db_start"] = "# Start PostgreSQL manually or via cloud provider"

    setup["env"] = "test -f .env.local || cp .env.example .env.local"

    if backend in ("payload", "payload-cms"):
        setup["db_migrate"] = "npx payload migrate"
    else:
        setup["db_migrate"] = f"{pkg_manager} run db:migrate"

    # ---------------------------------------------------------------
    # Validation commands (used by ralph.sh after each story)
    # ---------------------------------------------------------------
    commands["build"] = f"{pkg_manager} run build"
    commands["lint"] = f"{pkg_manager} run lint"
    commands["test"] = f"{pkg_manager} test"
    commands["typecheck"] = "npx tsc --noEmit"

    # ---------------------------------------------------------------
    # Dev commands
    # ---------------------------------------------------------------
    commands["dev"] = f"{pkg_manager} run dev"

    if database == "postgres" and deploy_target in ("docker", "docker_and_k8s_later"):
        commands["db_start"] = "docker compose up -d postgres"
        commands["db_stop"] = "docker compose down"

    if backend in ("payload", "payload-cms"):
        commands["db_migrate"] = "npx payload migrate"
        commands["db_seed"] = "npx payload seed"
    else:
        commands["db_migrate"] = f"{pkg_manager} run db:migrate"

    # ---------------------------------------------------------------
    # Capability-specific commands
    # ---------------------------------------------------------------
    if "scheduled-jobs" in capabilities:
        commands["jobs"] = f"{pkg_manager} run jobs"
        notes.append(
            "The 'jobs' command starts the background job runner. "
            "Configure it after implementing the automation story."
        )

    # ---------------------------------------------------------------
    # Notes
    # ---------------------------------------------------------------
    notes.insert(0,
        "These commands are pre-populated from the project stack. "
        "Update them if the actual project setup differs."
    )
    notes.append(
        "Run 'build' and 'lint' after every story. "
        "Run 'test' when test files exist."
    )
    notes.append(
        "Run 'typecheck' periodically to catch type errors early."
    )

    return {
        "commands": commands,
        "setup": setup,
        "notes": notes,
    }