"""Commands Engine.

Derives validation, setup, and development commands from
the project stack so that commands.json is pre-populated
and the ralph loop can validate from the first story.

This replaces the empty commands.json that was previously
generated by the openclaw bundle.
"""

from __future__ import annotations

from typing import Any

from initializer.engine.validation_contract import build_validation_bundle


def generate_commands(spec: dict[str, Any]) -> dict[str, Any]:
    """Generate commands + validation contract from the project spec."""
    return build_validation_bundle(spec)
